people:
- name: Emilie LaFleur
  age: 25
  job: milliner
  bio: Young hat maker with flair for design.
  values:
  - beauty
  - innovation
  goals:
  - open own shop
  - create perfect hat style
  start_place: The Hat Shop
- name: Auguste Dumont
  age: 42
  job: blacksmith
  bio: Experienced iron worker with strong hands.
  values:
  - hard work
  - family
  goals:
  - buy own forge
  - give children a good life
  start_place: The Forge
- name: Sophie Dupont
  age: 32
  job: dressmaker
  bio: Talented seamstress with eye for detail.
  values:
  - quality
  - community
  goals:
  - expand business
  - help those in need
  start_place: The Dress Shop
- name: Félix Moreau
  age: 29
  job: chemist
  bio: Curious scientist with passion for discovery.
  values:
  - knowledge
  - progress
  goals:
  - find cure for disease
  - publish scientific paper
  start_place: The Laboratory
- name: Colette Rousseau
  age: 50
  job: cook and innkeeper
  bio: Warm hostess with hearty cooking skills.
  values:
  - hospitality
  - generosity
  goals:
  - improve recipes
  - host famous guests
  start_place: The Inn
- name: Eugene Dubois
  age: 42
  job: blacksmith
  bio: Hammers hot metal for a living; tough but fair.
  values:
  - honesty
  - hard work
  goals:
  - make quality tools
  - pay off debts
  start_place: house2
- name: Léonie LaFleur
  age: 25
  job: milliner
  bio: Creates hats for the fashionable ladies; whimsical.
  values:
  - beauty
  - independence
  goals:
  - open own shop
  - travel to Paris
  start_place: La Maison de Modes
- name: Gustave Moreau
  age: 58
  job: notary public
  bio: Draws up documents; wise and experienced.
  values:
  - justice
  - respect
  goals:
  - help young families
  - write a book
  start_place: The Notary's Office
- name: Cécile Dumont
  age: 32
  job: teacher
  bio: Teaches children; patient and kind.
  values:
  - education
  - family
  goals:
  - improve school conditions
  - start a family
  start_place: The École
- name: Pierre Dupont
  age: 29
  job: grocer
  bio: Sells fresh produce; optimistic and friendly.
  values:
  - community
  - health
  goals:
  - expand his shop
  - help the poor
  start_place: The Market
- name: Eugene Dubois
  age: 42
  job: blacksmith
  bio: Hammers hot metal for a living; tough but fair.
  values:
  - honesty
  - hard work
  goals:
  - make quality tools
  - pay off debts
  start_place: house1
- name: Léonie LaFleur
  age: 25
  job: milliner
  bio: Creates hats for the fashionable ladies; whimsical.
  values:
  - beauty
  - independence
  goals:
  - open own shop
  - travel to Paris
  start_place: Lumière General Hospital
- name: Gustave Moreau
  age: 58
  job: notary public
  bio: Draws up documents; wise and experienced.
  values:
  - justice
  - respect
  goals:
  - help young families
  - write a book
  start_place: Lumière Public Pool
- name: Cécile Dumont
  age: 32
  job: teacher
  bio: Teaches children; patient and kind.
  values:
  - education
  - family
  goals:
  - improve school conditions
  - start a family
  start_place: Lumière Public Pool
- name: Pierre Dupont
  age: 29
  job: grocer
  bio: Sells fresh produce; optimistic and friendly.
  values:
  - community
  - health
  goals:
  - expand his shop
  - help the poor
  start_place: Lumière Community Center
- name: Eugene Dubois
  age: 42
  job: blacksmith
  bio: Hammers hot metal for a living; tough but fair.
  values:
  - honesty
  - hard work
  goals:
  - make quality tools
  - pay off debts
  start_place: Lumière Community Center
- name: Léonie LaFleur
  age: 25
  job: milliner
  bio: Creates hats for the fashionable ladies; whimsical.
  values:
  - beauty
  - independence
  goals:
  - open own shop
  - travel to Paris
  start_place: Lumière City Hall
- name: Gustave Moreau
  age: 58
  job: notary public
  bio: Draws up documents; wise and experienced.
  values:
  - justice
  - respect
  goals:
  - help young families
  - write a book
  start_place: Lumière General Hospital
- name: Cécile Dumont
  age: 32
  job: teacher
  bio: Teaches children; patient and kind.
  values:
  - education
  - family
  goals:
  - improve school conditions
  - start a family
  start_place: Lumière City Hall
- name: Pierre Dupont
  age: 29
  job: grocer
  bio: Sells fresh produce; optimistic and friendly.
  values:
  - community
  - health
  goals:
  - expand his shop
  - help the poor
  start_place: Lumière Police Station
