city: "Lumi\xE8re"
overview: "Lumi\xE8re is a vibrant small city."
places:
- name: "Lumi\xE8re City Hall"
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: "Lumi\xE8re Central Park"
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: "Lumi\xE8re Library"
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: "Lumi\xE8re General Hospital"
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: "Lumi\xE8re Elementary School"
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: "Lumi\xE8re Police Station"
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: "Lumi\xE8re Community Center"
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: "Lumi\xE8re Main Bakery"
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: "Lumi\xE8re Restaurant"
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: "Lumi\xE8re Public Bath"
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: Laundry Row
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: "H\xF4tel de la Paix"
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: Clos de la Fontaine
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: "Rue de la R\xE9publique"
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: "Place de la Libert\xE9"
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: Rue de la Bourse
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: The Forge
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: "Madame Dupr\xE9's Dress Salon"
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: The Notary's Office
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: "Lumi\xE8re Schoolhouse"
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: The Post Office
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: LaFleur Forge
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: Patel Millinery
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: Reed Law Office
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: Kim's Teacart
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: Dupre School
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: Dupont's Clocks
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: LaFleur's Millinery
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: LeCoeur's Vintner
  category: unknown
  description: "A notable location in Lumi\xE8re."
- name: Moreau's Apothecary
  category: unknown
  description: "A notable location in Lumi\xE8re."
houses: []
streets: []
connections:
- - "Lumi\xE8re Main Bakery"
  - LaFleur Forge
- - Dupre School
  - LaFleur Forge
- - Dupont's Clocks
  - LaFleur Forge
- - "Lumi\xE8re City Hall"
  - Dupont's Clocks
- - Reed Law Office
  - Dupont's Clocks
- - The Forge
  - LaFleur Forge
- - "H\xF4tel de la Paix"
  - Dupont's Clocks
- - "Madame Dupr\xE9's Dress Salon"
  - Dupont's Clocks
- - "Lumi\xE8re Restaurant"
  - The Forge
- - "Place de la Libert\xE9"
  - "Lumi\xE8re City Hall"
- - "Lumi\xE8re Police Station"
  - The Forge
- - "Lumi\xE8re Elementary School"
  - The Forge
- - "Lumi\xE8re Schoolhouse"
  - "Place de la Libert\xE9"
- - "Lumi\xE8re Community Center"
  - The Forge
- - "Lumi\xE8re General Hospital"
  - "Lumi\xE8re Schoolhouse"
- - The Notary's Office
  - The Forge
- - Moreau's Apothecary
  - "Lumi\xE8re Restaurant"
- - The Post Office
  - "Place de la Libert\xE9"
- - Kim's Teacart
  - "Lumi\xE8re Main Bakery"
- - Laundry Row
  - The Post Office
- - Clos de la Fontaine
  - The Notary's Office
- - "Rue de la R\xE9publique"
  - "Lumi\xE8re Restaurant"
- - Patel Millinery
  - Kim's Teacart
- - Rue de la Bourse
  - "Rue de la R\xE9publique"
- - LeCoeur's Vintner
  - LaFleur Forge
- - "Lumi\xE8re Central Park"
  - "Place de la Libert\xE9"
- - LaFleur's Millinery
  - "Lumi\xE8re Main Bakery"
- - "Lumi\xE8re Library"
  - "Lumi\xE8re Schoolhouse"
- - "Lumi\xE8re Public Bath"
  - Rue de la Bourse
- - "Lumi\xE8re Public Bath"
  - "Lumi\xE8re Library"
- - Kim's Teacart
  - Rue de la Bourse
- - "Lumi\xE8re City Hall"
  - "Lumi\xE8re Main Bakery"
- - "Lumi\xE8re Main Bakery"
  - Moreau's Apothecary
- - Reed Law Office
  - "Lumi\xE8re Elementary School"
- - Laundry Row
  - The Forge
- - "Lumi\xE8re Elementary School"
  - The Notary's Office
- - Clos de la Fontaine
  - "Lumi\xE8re Public Bath"
- - Dupont's Clocks
  - "Lumi\xE8re Schoolhouse"
- - The Forge
  - "Rue de la R\xE9publique"
