first_names:
- Abelard
- Abram
- Achille
- Adelaide
- Adelard
- Adolph
- Adolphe
- Adrien
- Adrienne
- Adèle
- Agnata
- Agnes
- Agnette
- Agnès
- Aimé
- Alfred
- Alicea
- Aline
- Alixandre
- Alphons
- Alphonse
- Alphonsine
- Amabel
- Amabelle
- Amande
- Amelia
- Amédée
- Amélie
- Anastasia
- Anastasie
- Andrews
- Andréanne
- Andrée
- Angelique
- Angèle
- Anicette
- Annabelle
- Annie
- Anselm
- Antoine
- Antoinette
- Antoinnette
- Antonie
- Archange
- Archibald
- Aristide
- Armande
- Arnold
- Arsène
- Arthur
- Astrid
- Astridde
- Athos
- Augustin
- Augustinette
- Aurelie
- Aurelius
- Aurore
- Aurélien
- Autelina
- Avis
- Balthazar
- Balthazarine
- Balthilda
- Barbara
- Barnaby
- Bartholomée
- Barthélemy
- Baudouin
- Baudouinette
- Beatrice
- Beatrix
- Benedict
- Benjamin
- Benjaminne
- Bernadette
- Bernadine
- Bertha
- Berthe
- Berton
- Bessie
- Blanch
- Blanche
- Blandina
- Blandine
- Brunhilde
- Bruno
- Brunolette
- Calantha
- Calista
- Calixte
- Calixtie
- Catharine
- Cecila
- Cecilia
- Cedric
- Cedrine
- Charlotte
- Circe
- Clarence
- Claude
- Clayton
- Clemente
- Clémence
- Constance
- Cornelius
- Cornélie
- Cyprien
- Cyprienne
- Célestine
- Césarine
- Daisy
- Damien
- Daphne
- Daphné
- Delia
- Delphine
- Denisette
- Diamante
- Dominic
- Dominique
- Donovan
- Dorinne
- Dorothie
- Dorothy
- Désirée
- Edith
- Eleanor
- Elgiva
- Eliza
- Elizabeth
- Ellen
- Elodie
- Eloise
- Eloïse
- Elsie
- Elspeth
- Elvina
- Emily
- Emmeline
- Estelle
- Esther
- Ethel
- Euclide
- Eugene
- Eugenie
- Eulalia
- Eulalie
- Eulalina
- Euphémie
- Evander
- Ezechiel
- Fanny
- Felice
- Felicita
- Ferdinand
- Fidèle
- Fleur
- Flora
- Florence
- Florentine
- Frances
- Francis
- Françoise
- Fulgencie
- Félicie
- Félix
- Gabrielle
- Gabriot
- Gaspard
- Gaspardina
- Gaspardine
- Gauthier
- Georgeanna
- Georgette
- Gertrude
- Gideon
- Gladys
- Godfrey
- Gracia
- Gracie
- Griselda
- Hannah
- Harriet
- Hattie
- Hedwiga
- Helena
- Helene
- Henrietta
- Herbert
- Hester
- Hildegarde
- Hippolyte
- Hortense
- Hortensia
- Hortensienne
- Hughes
- Ida
- Idonea
- Irene
- Irma
- Irvine
- Irénée
- Isabel
- Ita
- Ivoine
- Ivone
- Ivonne
- Jemima
- Jemimah
- Jennie
- Johanna
- Josephine
- Jourdaine
- Justine
- Jérôme
- Katharina
- Katharine
- Katherine
- Keroual
- Kerstin
- Lambert
- Lamberte
- Lancelot
- Lancelote
- Laura
- Lavinia
- Lavynia
- Leona
- Leonard
- Leonora
- Leontine
- Lewis
- Lillian
- Louisa
- Louise
- Lucetta
- Lucy
- Lydia
- Lysander
- Mabel
- Mabelle
- Madeleine
- Magdalena
- Malvina
- Marcelline
- Margaret
- Margarita
- Marguerite
- Mariah
- Marie
- Marion
- Martha
- Mary
- Maryanne
- Marye
- Matilda
- Maude
- Maurice
- Mauricette
- Mauricienne
- Maybelle
- Melinda
- Minnie
- Nadine
- Nadège
- Narcisse
- Nathalie
- Nathaniel
- Nathanielle
- Nativida
- Nedra
- Nellie
- Norma
- Odette
- Olive
- Oliver
- Olivette
- Olympe
- Omer
- Ondinea
- Ophelia
- Oscar
- Pamela
- Parke
- Pascal
- Pascaline
- Pauline
- Paxina
- Pearl
- Penelope
- Perceval
- Percine
- Philomena
- Philomène
- Pierre
- Pierrelette
- Pétronille
- Quentin
- Quintilienne
- Quintin
- Quintine
- Rachel
- Rachilde
- Raphaël
- Roderica
- Roderick
- Roderique
- Ronald
- Rosalie
- Rowena
- Ruth
- Sabin
- Sabina
- Sabinette
- Sabinne
- Salome
- Samuel
- Sara
- Sarah
- Selma
- Sibylle
- Silas
- Simone
- Sophia
- Stanley
- Stella
- Susanna
- Sylviane
- Thaddeus
- Theodora
- Theodore
- Theodoric
- Therese
- Thibaut
- Thibautte
- Thomasine
- Thérèse
- Tibaulde
- Tibault
- Tibautte
- Ursula
- Ursulene
- Ursulina
- Ursuline
- Valentine
- Violet
- Vital
- Vitaline
- Vivian
- Vivianne
- Vivienne
- Walter
- Weldon
- Wenceslade
- Wenceslas
- Wenceslasine
- Wilhelmina
- Willard
- Willie
- Winifred
- Winston
- Xanthe
- Xaviera
- Xavierine
- Xenophonie
- Xénophon
- Xénophonie
- Yolande
- Yseulte
- Zelda
- Zephirin
- Zephirine
- Zéphirine
- Étienne
last_names:
- Abrahams
- Adair
- Akerman
- Alcock
- Aldridge
- Allenby
- Alsop
- Althorpe
- Ambler
- Amesbury
- Amory
- Anderson
- Arden
- Argent
- Ashton
- Ashurst
- Astley
- Atkin
- Bacon
- Baldwin
- Bancroft
- Bardwell
- Barnard
- Barrington
- Bartlett
- Bateman
- Bateson
- Baynes
- Beadle
- Beaumont
- Beddowes
- Bellamy
- Bennett
- Berkeley
- Berry
- Bickerton
- Bickford
- Biddle
- Biddlecomb
- Biggs
- Bilbie
- Birch
- Birdsell
- Birtwhistle
- Bissell
- Bissett
- Bissey
- Bland
- Blandy
- Blore
- Blount
- Bloxham
- Blythe
- Boddy
- Bondfield
- Boothby
- Booton
- Bostock
- Bostocke
- Bowden
- Bowker
- Bownes
- Brabazon
- Brabyn
- Bradley
- Bradwell
- Bramwell
- Brearton
- Brentnall
- Brett
- Brewer
- Bridgeman
- Bridges
- Bristowe
- Brittain
- Brocklebank
- Bromley
- Brooke
- Brookesby
- Broughton
- Browne
- Bryden
- Buckingham
- Buller
- Bullocke
- Burbidge
- Burgess
- Burgesse
- Burland
- Burnaby
- Burroughes
- Butler
- Butterworth
- Byng
- Cadogan
- Caldwell
- Callander
- Calvert
- Camden
- Campion
- Carden
- Carlisle
- Carroll
- Carruthers
- Carteret
- Cartwright
- Cary
- Casey
- Caswall
- Cavendish
- Cawdrey
- Chadwick
- Chamberlayne
- Chambers
- Chance
- Chaplin
- Charke
- Charlesworth
- Charnock
- Chartres
- Chatfield
- Cheek
- Cheesman
- Cheney
- Chetwynd
- Child
- Chipchase
- Churchill
- Cicely
- Clare
- Claridge
- Clarke
- Claydon
- Clement
- Cleveland
- Clinch
- Cliney
- Cobham
- Cockburne
- Coghill
- Colby
- Colebatch
- Collett
- Collins
- Commins
- Compton
- Coningham
- Constable
- Conyers
- Cooper
- Copeley
- Coppin
- Corbet
- Cordell
- Cornwall
- Cosgrave
- Cotesworth
- Cotterill
- Cotton
- Coulsdon
- Courtenay
- Couthurst
- Coxall
- Coxe
- Coxwell
- Cranston
- Craythorne
- Cressy
- Criddle
- Cripps
- Crombie
- Crompton
- Crookshank
- Crowther
- Crymble
- Culpeper
- Cumming
- Cunningham
- Dale
- Dalton
- Davenport
- Davey
- Dawson
- Dawtrey
- Dayrell
- Deacon
- Dean
- Dearing
- Dench
- Denman
- Derbyshire
- Dickensoe
- Dickenson
- Doddridge
- Dodsworth
- Doig
- Dolben
- Donkin
- Dorsett
- Doughty
- Dowding
- Dowsing
- Drewe
- Drewry
- Drury
- Dufton
- Dunbar
- Duncan
- Dundas
- Dunn
- Dunton
- Eaton
- Edwards
- Egerton
- Eggleston
- Elcock
- Elliot
- Ellis
- Elverson
- Emmott
- Estcourt
- Evans
- Everard
- Eyre
- Faber
- Falconer
- Fallowes
- Farley
- Farquharson
- Farrow
- Farthing
- Feilding
- Fellows
- Feltham
- Fetherstone
- Fetherstonhaugh
- Fielding
- Figgis
- Filby
- Finch
- Finlayson
- Fishbourne
- Fisher
- Fitton
- Fitzgerald
- Fitzherbert
- Fitzwilliam
- Flintoft
- Flynn
- Forde
- Fortescue
- Gadby
- Gage
- Gale
- Gallagher
- Galloway
- Gardiner
- Garland
- Garnett
- Garth
- Gascoigne
- Gaskell
- Gatley
- Gault
- Gawthrop
- Gaydon
- Geoffrey
- George
- Gibbings
- Gibbons
- Gibson
- Gilbertson
- Gillespie
- Gilliland
- Gillingwater
- Gilmore
- Gilmour
- Gilpin
- Glover
- Goddard
- Goffe
- Goodere
- Goodspeed
- Goodwin
- Gordon
- Gough
- Govan
- Gower
- Granger
- Grantley
- Gray
- Grayston
- Greaves
- Greenway
- Gregory
- Grey
- Griffiths
- Gritten
- Hadfield
- Hallam
- Harland
- Harman
- Harrison
- Haselden
- Hastings
- Hawes
- Haydon
- Heathcote
- Heaton
- Hemsworth
- Herbertson
- Heywood
- Hickling
- Hildyard
- Hillier
- Hobson
- Hodges
- Hoggan
- Holden
- Holmes
- Hopkins
- Hornby
- Houghton
- Howard
- Howes
- Hubbard
- Hughes
- Hull
- Hume
- Humphries
- Huntley
- Hurst
- Hyde
- Inglesfield
- Ingleton
- Irving
- Isaacson
- Jagger
- Jarvis
- Jebb
- Jefford
- Jenkins
- Jerome
- Jobson
- Johnson
- Joiner
- Jones
- Keast
- Kempthorne
- Kempton
- Kenning
- Kentish
- Kerridge
- Keyworth
- Kidston
- Kimberley
- Kingdon
- Kinnersley
- Knighton
- Lambert
- Lambourn
- Lancaster
- Langdale
- Langford
- Langton
- Lascelles
- Lathom
- Lauder
- Lavender
- Laycock
- Leech
- Leggatt
- Leigh
- Leveson
- Lightfoot
- Lingwood
- Lisle
- Litchfield
- Littlejohns
- Locke
- Lockerby
- Lockhart
- Longley
- Looker
- Lord
- Lorne
- Lowther
- Luard
- Lushington
- Luttrell
- Lyttelton
- Mackenzie
- Macpherson
- Maddock
- Maddocks
- Maiden
- Majoribanks
- Mallinson
- Mansfield
- Marchbank
- Marden
- Margetts
- Marmaduke
- Marshall
- Martin
- Mason
- Massingberd
- Mather
- Mattinson
- Mawson
- Maxwell
- Mayo
- Meade
- Medhurst
- Melville
- Merriman
- Miers
- Milburne
- Millington
- Mills
- Milne
- Milton
- Minchin
- Mitford
- Monkton
- Montague
- Moody
- Moorcroft
- Morewood
- Morley
- Morrissey
- Morton
- Mossop
- Mottershead
- Mowbray
- Mulock
- Munday
- Murdoch
- Myres
- Naylor
- Neilson
- Newbery
- Newton
- Nicolson
- Nightingale
- Noel
- Nokes
- Nuttall
- Nutting
- Oates
- Odding
- Offley
- Oldfield
- Oliver
- Ormond
- Osborne
- Overbury
- Packer
- Paget
- Palmerston
- Parker
- Parrington
- Parry
- Passingham
- Paterson
- Payler
- Peake
- Pearson
- Pedder
- Pemberton
- Penman
- Perceval
- Petrie
- Pettigrew
- Phelps
- Phillips
- Pickering
- Plumer
- Plympton
- Pocock
- Polhill
- Pollard
- Porter
- Potter
- Poulton
- Powney
- Preece
- Preston
- Pritchard
- Proctor
- Pullen
- Pym
- Quicke
- Quinlan
- Ramsay
- Rankin
- Reade
- Redfern
- Redmond
- Reed
- Reeves
- Repton
- Rhodes
- Richards
- Richardson
- Rickard
- Ridgeway
- Ringwood
- Robinson
- Robson
- Rockefeller
- Rogers
- Rolfe
- Romilly
- Roper
- Roscow
- Rosebery
- Rossiter
- Rowe
- Rowland
- Rowley
- Royds
- Rumbold
- Sanderson
- Sandon
- Savage
- Sayce
- Scudamore
- Seabrook
- Selwyn
- Seton
- Shadwell
- Sharpe
- Sharples
- Shawe
- Shephard
- Shipley
- Shorter
- Shrewsbury
- Silvester
- Simpson
- Skelton
- Sleight
- Slingsby
- Smithers
- Snellgrove
- Southey
- Spalding
- Sparkes
- Sparrow
- Spearing
- Spearman
- Spencer
- Spenlow
- Sprattling
- Stafford
- Stanbury
- Stanhope
- Staples
- Starkie
- Steere
- Stephens
- Stockdale
- Stonehouse
- Storey
- Stratton
- Streete
- Strong
- Sullivan
- Summers
- Surtees
- Sutton
- Talbot
- Talbott
- Taplin
- Tarleton
- Tatham
- Tattersall
- Tayler
- Tennent
- Terrington
- Thistlethwayte
- Thomas
- Thompson
- Thornton
- Thorp
- Tickell
- Timbrell
- Tindal
- Titchmarsh
- Toft
- Tomkins
- Tonkin
- Torrens
- Townsend
- Trafford
- Tranter
- Tregear
- Trevanion
- Trevelyan
- Trewartha
- Trippett
- Trowbridge
- Tryon
- Turner
- Twistleton
- Tyler
- Tyrell
- Udall
- Underhill
- Upcher
- Vaux
- Vizard
- Wadham
- Wakefield
- Walker
- Walsham
- Wardell
- Wareing
- Waring
- Warrington
- Warwick
- Waterman
- Weaver
- Weir
- Wellington
- Welsh
- Wentworth
- Westbrook
- Whalley
- Whatley
- Wheelhouse
- Whitehead
- Whitfield
- Whitley
- Whitmore
- Whyte
- Wickham
- Wiffin
- Wilbraham
- Wilkins
- Williamson
- Wills
- Wilmot
- Wiltshire
- Wimborne
- Wingate
- Winnall
- Winstanley
- Winterbottom
- Winterton
- Wise
- Wiston
- Witherspoon
- Wolfenden
- Wollaston
- Woolsey
- Worthington
- Wrangham
- Wray
- Wrightson
- Wychwood
- Yarde
- Yates
- Yeats
- Yorkshire
