people:
- name: Ethan Patel
  age: 32
  job: software engineer
  bio: Codes all day; loves hiking on weekends.
  values:
  - integrity
  - innovation
  - community
  goals:
  - launch own startup
  - improve coding skills
  - hike to the top of Redwood's highest peak
  start_place: The Redwood Inn
- name: Lena Kim
  age: 25
  job: nurse
  bio: Cares for patients; enjoys yoga in her free time.
  values:
  - compassion
  - empathy
  - self-care
  goals:
  - become a specialist
  - start a wellness blog
  - attend a yoga retreat
  start_place: Redwood General Hospital
- name: Jaden Lee
  age: 41
  job: restaurant owner
  bio: Serves up burgers; loves playing guitar.
  values:
  - hospitality
  - family
  - music
  goals:
  - expand the restaurant
  - learn to play jazz
  - start a music school
  start_place: Jaden's Eats
- name: Sofia Rodriguez
  age: 29
  job: teacher
  bio: Educates students; enjoys reading in her free time.
  values:
  - education
  - equality
  - literacy
  goals:
  - become a department head
  - start a book club
  - travel to teach abroad
  start_place: Redwood Elementary School
- name: Cameron Brown
  age: 58
  job: retired police officer
  bio: Serves the community; loves gardening.
  values:
  - service
  - justice
  - nature
  goals:
  - start a community garden
  - become a mentor
  - travel to visit grandkids
  start_place: The Redwood Police Department
- name: Emily Patel
  age: 32
  job: nurse
  bio: Caring nurse with a love for helping others.
  values:
  - compassion
  - integrity
  goals:
  - get promoted
  - find a long-term partner
  start_place: The Redwood Inn
- name: Liam Chen
  age: 25
  job: software engineer
  bio: Tech-savvy young professional with a passion for gaming.
  values:
  - innovation
  - community
  goals:
  - launch own startup
  - attend music festivals
  start_place: The Cozy Cupboard
- name: Sophia Rodriguez
  age: 41
  job: small business owner (bakery)
  bio: Warm-hearted bakery owner with a love for sweet treats.
  values:
  - family
  - generosity
  goals:
  - expand the bakery
  - start a family
  start_place: The Sweet Spot Bakery
- name: Julian Lee
  age: 50
  job: retired teacher
  bio: Witty retired teacher with a love for gardening.
  values:
  - knowledge
  - nature
  goals:
  - travel the world
  - write a book
  start_place: The Redwood Retirement Home
- name: Ava Morales
  age: 22
  job: student (psychology)
  bio: Aspiring psychologist with a love for social justice.
  values:
  - equality
  - empathy
  goals:
  - graduate with honors
  - land an internship
  start_place: The Redwood University Dorms
- name: Ethan Kim
  age: 32
  job: software engineer
  bio: Co-founder of a startup; loves coding marathons.
  values:
  - innovation
  - collaboration
  - work-life balance
  goals:
  - launch new product
  - hire team members
  - improve company culture
  start_place: The Redwood Hub
- name: Luna Patel
  age: 25
  job: nurse practitioner
  bio: Recent grad; passionate about community health.
  values:
  - compassion
  - education
  - social justice
  goals:
  - complete residency
  - launch non-profit
  - improve healthcare access
  start_place: Redwood Medical Center
- name: Julian Sanchez
  age: 41
  job: small business owner
  bio: Owner of a local bakery; loves experimenting with recipes.
  values:
  - quality
  - customer service
  - community involvement
  goals:
  - expand product line
  - hire staff
  - increase online presence
  start_place: Sanchez's Sweet Treats
- name: Ava Lee
  age: 29
  job: artist and art teacher
  bio: Freelance artist; loves teaching kids to paint.
  values:
  - creativity
  - self-expression
  - inspiration
  goals:
  - launch online course
  - exhibit work in gallery
  - improve teaching skills
  start_place: The Artisan's Studio
- name: Cameron Reed
  age: 55
  job: retired teacher and coach
  bio: Former high school football coach; loves mentoring young athletes.
  values:
  - sportsmanship
  - teamwork
  - personal growth
  goals:
  - start coaching clinic
  - mentor student-athletes
  - stay active in community
  start_place: Redwood High School
- name: Jaxson Reed
  age: 35
  job: IT Specialist
  bio: Works from home; loves video games.
  values:
  - integrity
  - productivity
  - fun
  goals:
  - launch a gaming channel
  - improve coding skills
  - buy a new PC
  start_place: The Redwood Inn
- name: Luna Torres
  age: 22
  job: Baker
  bio: Works at the local bakery; loves baking.
  values:
  - creativity
  - kindness
  - fresh air
  goals:
  - open her own bakery
  - learn to make croissants
  - start a garden
  start_place: The Cozy Cupcake Cafe
- name: Ethan Patel
  age: 29
  job: Doctor
  bio: Works at the local hospital; loves medicine.
  values:
  - compassion
  - knowledge
  - helping others
  goals:
  - become a specialist
  - start a medical non-profit
  - read more books
  start_place: The Redwood Medical Center
- name: Maya Ramos
  age: 41
  job: Teacher
  bio: Teaches at the local elementary school; loves kids.
  values:
  - patience
  - education
  - community
  goals:
  - become a principal
  - start a literacy program
  - travel more
  start_place: The Redwood Elementary School
