city: Redwood
places:
  - name: Street
    neighbors: [Apartment, Cafe, Office]
    capabilities: []
    purpose: Main thoroughfare.
  - name: Apartment
    neighbors: [Street]
    capabilities: [sleep, food_home]
    purpose: Small residential block.
  - name: Cafe
    neighbors: [Street]
    capabilities: [food, coffee]
    purpose: Cozy cafe popular with locals.
    vendor:
      prices: { coffee: 3.5, pastry: 4.0 }
      stock:  { coffee: 999, pastry: 40 }
  - name: Office
    neighbors: [Street]
    capabilities: [work_dev]
    purpose: Startup office space.
